### ISSUE TITLE
回旋镖合成材料数量有误

### ISSUE THREAD

**Issue by yzhang-gh** [tpxxn/JiHuangBaiKeForUWP#3]
![image](https://user-images.githubusercontent.com/7588612/30354722-c38955b2-9860-11e7-9fb1-0f45b181b9f7.png)

![image](https://user-images.githubusercontent.com/7588612/30354733-e9e60ffc-9860-11e7-9b7d-e30bbb63a9c7.png)

只需要一个木板

---

另外如果能给武器都加上伤害值就更好了

**Comment by tpxxn** [comment]
你看的这个百科不是我做的，是张高兴做的，他已经不维护了。
我的应用在应用商店里名字叫 饥荒百科全书 by tpxxn，装备的伤害等属性写在物品-装备里。
回旋镖的材料确实有误。
感谢您的回复~

**Comment by tpxxn** [comment]
![image](https://user-images.githubusercontent.com/10829204/30359595-69f3927e-987e-11e7-9c6a-24c39b7ae381.png)

**Comment by yzhang-gh** [comment]
嗯，截图的时候是用的张高兴的，是后来懒得再截了😂
